### ISSUE TITLE
Unable to build clients

### ISSUE THREAD

**Issue by ekuznetsov139** [ROCmSoftwarePlatform/rocBLAS#958]
I am unable to build clients on Ubuntu 18.04 (gcc 7.4.0), with either the rocm-3.0 tag or the head of develop.

Building with install.sh -c fails due to the error from #845, and I'm unable to patch the source of Tensile to get around it because install.sh just wipes everything and checks out the code from scratch. 

I tried to build clients only by hand. The process is not clearly documented but I did the following. 
* Create clients/build
* Change into clients/build
* Run cmake -DBUILD_CLIENTS_BENCHMARKS=ON ..
* Run make

This fails too. If I run cmake as above, with no additional environment variables, it fails with a ton of errors starting with

> /home/zen/devel/rocBLAS/clients/benchmarks/../include/rocblas.hpp:36:1: error: explicit template specialization cannot have a storage class
>  static constexpr auto rocblas_scal<float> = rocblas_sscal;
>  ^~~~~~
> 

If, instead, I do
CXX=/opt/rocm/bin/hcc cmake -DBUILD_CLIENTS_BENCHMARKS=ON ..
or
CXX=/opt/rocm/bin/hipcc cmake -DBUILD_CLIENTS_BENCHMARKS=ON ..

it fails with

> 
> /home/zen/devel/rocBLAS/clients/benchmarks/../include/rocblas_datatype2string.hpp:21:11: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
> constexpr auto rocblas2char_operation(rocblas_operation value)
>           ^

I figured out how to force rocBLAS to use C++14, but that just kicks the can down the road a bit, since then it fails with

> 
> [ 50%] Building CXX object benchmarks/CMakeFiles/rocblas-bench.dir/client.cpp.o
> In file included from /home/zen/devel/rocBLAS/clients/benchmarks/client.cpp:7:
> In file included from /home/zen/devel/rocBLAS/clients/benchmarks/../include/rocblas_data.hpp:8:
> In file included from /home/zen/devel/rocBLAS/clients/benchmarks/../include/rocblas_arguments.hpp:10:
> /home/zen/devel/rocBLAS/clients/benchmarks/../include/rocblas_math.hpp:30:48: error: use of undeclared identifier 'is_complex'; did you mean '_Complex'?
> template <typename T, typename std::enable_if<!is_complex<T>, int>::type = 0>
>                                                ^~~~~~~~~~
>                                                _Complex
> /home/zen/devel/rocBLAS/clients/benchmarks/../include/rocblas_math.hpp:30:48: error: expected unqualified-id
> /home/zen/devel/rocBLAS/clients/benchmarks/../include/rocblas_math.hpp:30:69: error: parameter declarator cannot be qualified
> template <typename T, typename std::enable_if<!is_complex<T>, int>::type = 0>
>                                                                   ~~^

What's the correct build process?

**Comment by ekuznetsov139** [comment]
One major outstanding source of trouble was that the code here https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/library/include/rocblas-complex-types.h#L12 expects to find either `__HCC__` or `__HIPCC__` defined. But the closest I have to these macros in the command line of hcc is `__HIP_PLATFORM_HCC__`.

After correcting rocblas-complex-types.h, I run into several more errors related to bfloat16 (e.g. " error: cannot convert 'rocblas_bfloat16' to 'float' without a conversion operator"). 

I've managed to build rocblas-bench by disabling several bfloat16 functions.
